"""TradePlan — frozen, journaled, deterministic. Built from an emitted bar.

Entry = limit at the setup close. Stop = beyond the opposing confirmed swing by
STOP_ATR_BUFFER * ATR. qty = R_USD / per-share risk (jesse math). tp1/2/3 =
+1R/+2R/+4R, each snapped to a confluent level (VAH/fib ext/OI wall) when within
LEVEL_SNAP_TOLERANCE_PCT. TTL = 3 setup-TF bars. Both sides are generated by the
scan; each is gated independently. Plans carry the full per-family breakdown for
explainability.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timedelta

from .. import config
from ..mtf import resample as _resample
from . import scorer, sizing

# Feature columns offered as confluent snap targets for take-profits.
SNAP_LEVEL_COLS = ("vp_vah", "vp_val", "fib_ext_1272", "fib_ext_1618",
                   "opt_call_wall", "opt_put_wall")


@dataclass(frozen=True)
class TradePlan:
    symbol: str
    setup_tf: str
    side: str                 # "long" | "short"
    created_at: str
    expires_at: str
    entry: float
    stop: float
    risk_per_share: float
    qty: float
    tp1: float
    tp2: float
    tp3: float
    tp_fractions: tuple
    combined: float
    regime: str
    levels_used: dict
    breakdown: dict

    def to_dict(self) -> dict:
        d = asdict(self)
        d["tp_fractions"] = list(self.tp_fractions)
        return d


def _finite(x) -> bool:
    try:
        return x is not None and x == x and abs(x) != float("inf")
    except Exception:  # noqa: BLE001
        return False


def snap(target: float, levels, side: str, entry: float,
         tol_pct: float = config.LEVEL_SNAP_TOLERANCE_PCT) -> tuple[float, float | None]:
    """Snap `target` to the nearest confluent level within tol_pct, but only to a
    level that stays on the profit side of entry (a snap must never pull a TP to or
    through entry). Returns (price, level_used_or_None)."""
    best, best_d = None, None
    for lv in levels:
        if not _finite(lv) or target == 0:
            continue
        if side == "long" and lv <= entry:      # long TP must stay above entry
            continue
        if side == "short" and lv >= entry:      # short TP must stay below entry
            continue
        d = abs(lv - target) / abs(target)
        if d <= tol_pct and (best_d is None or d < best_d):
            best, best_d = lv, d
    return (best, best) if best is not None else (target, None)


def build_plan(*, symbol: str, setup_tf: str, side: str, close: float, atr: float,
               swing_high: float, swing_low: float, combined: float, regime: str,
               breakdown: dict, snap_levels=None, now: datetime) -> TradePlan | None:
    """Construct a TradePlan, or None if the geometry is invalid (risk <= 0)."""
    if not (_finite(close) and _finite(atr) and atr > 0):
        return None
    entry = float(close)
    if side == "long":
        if not _finite(swing_low):
            return None
        stop = float(swing_low) - config.STOP_ATR_BUFFER * atr
    elif side == "short":
        if not _finite(swing_high):
            return None
        stop = float(swing_high) + config.STOP_ATR_BUFFER * atr
    else:
        return None

    risk = abs(entry - stop)
    if risk <= 0 or (side == "long" and stop >= entry) or (side == "short" and stop <= entry):
        return None
    qty = sizing.position_size(entry, stop)

    levels = list(snap_levels or [])
    tps, used = [], {}
    prev = entry
    for i, m in enumerate(config.TP_MULTIPLES, start=1):
        raw = sizing.target_for_r(entry, stop, m, side)
        price, lv = snap(raw, levels, side, entry)
        # keep TPs strictly monotonic away from entry; else fall back to the raw R level
        if (side == "long" and price <= prev) or (side == "short" and price >= prev):
            price, lv = raw, None
        tps.append(round(price, 4))
        prev = price
        if lv is not None:
            used[f"tp{i}"] = lv

    delta = _resample.tf_delta(setup_tf) if setup_tf != "1m" else timedelta(minutes=1)
    return TradePlan(
        symbol=symbol, setup_tf=setup_tf, side=side,
        created_at=now.isoformat(),
        expires_at=(now + config.PLAN_TTL_SETUP_BARS * delta).isoformat(),
        entry=round(entry, 4), stop=round(stop, 4), risk_per_share=round(risk, 4),
        qty=round(qty, 4), tp1=tps[0], tp2=tps[1], tp3=tps[2],
        tp_fractions=tuple(config.TP_FRACTIONS), combined=round(float(combined), 4),
        regime=regime, levels_used=used, breakdown=breakdown,
    )


def plans_from_features(feat, symbol: str, setup_tf: str) -> list[dict]:
    """Emit TradePlan dicts for every emit_long/emit_short bar in a features frame
    (from pipeline.features_for_tf). The bar timestamp is the plan's `now`. Reused
    by the live scan and the backtest so both build identical plans."""
    plans: list[dict] = []
    for ts, row in feat.iterrows():
        for side, flag in (("long", "emit_long"), ("short", "emit_short")):
            if not bool(row.get(flag)):
                continue
            levels = [row.get(c) for c in SNAP_LEVEL_COLS]
            p = build_plan(symbol=symbol, setup_tf=setup_tf, side=side,
                           close=row["close"], atr=row.get("atr"),
                           swing_high=row.get("swing_high"), swing_low=row.get("swing_low"),
                           combined=row.get("combined", 0.0), regime=row.get("regime", ""),
                           breakdown=scorer.breakdown(row), snap_levels=levels,
                           now=ts.to_pydatetime())
            if p is not None:
                plans.append(p.to_dict())
    return plans
